# Generated by Django 4.2.3 on 2023-07-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iveri', '0002_personaldetails_first_name_personaldetails_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='phone_number',
        ),
    ]
